<?php

namespace AppBundle\Repository;

/**
 * GuideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuideRepository extends \Doctrine\ORM\EntityRepository
{
}
