<?php

namespace AppBundle\Repository;

/**
 * PaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaintRepository extends \Doctrine\ORM\EntityRepository
{
}
