<?php

namespace AppBundle\Repository;

/**
 * StyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StyleRepository extends \Doctrine\ORM\EntityRepository
{
}
