<?php

namespace AppBundle\Repository;

/**
 * TechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechRepository extends \Doctrine\ORM\EntityRepository
{
}
